# Generated by Django 2.2.4 on 2019-09-09 06:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.CharField(max_length=50, verbose_name='距離')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='計測日時')),
            ],
            options={
                'verbose_name': '距離',
                'verbose_name_plural': '距離',
                'db_table': 'distance',
            },
        ),
    ]
