# Generated by Django 2.2.4 on 2019-09-10 06:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('distance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='distance',
            name='source',
            field=models.CharField(max_length=20, null=True, verbose_name='ソース'),
        ),
        migrations.AlterField(
            model_name='distance',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='時刻'),
        ),
    ]
